// Company data. Each entry: { id, industry, name, phone, city, note }
// `id` must be stable & unique — it's the key used to store call outcomes in localStorage.
// Industry labels: "Plumbers", "Electricians", "Mechanics", "Restaurants", "Car Washes",
// "HVAC", "Pest Control", "Lawn Care & Landscaping", "Carpet Cleaning", "Garage Doors",
// "Roofing & Gutters", "Water Softeners", "Dentists", "Chiropractors",
// "Real Estate & Mortgage", "Home Security & Smart Home".
// Utah County businesses. Phone numbers researched from public listings — verify before relying on them.
window.COMPANIES = [
  // --- Plumbers ---
  { id: "plumbers-1",  industry: "Plumbers", name: "Blue Plumbing and Drain Cleaning", phone: "385-325-6400", city: "Orem", note: "Serves Provo/Orem/Springville; 24/7" },
  { id: "plumbers-2",  industry: "Plumbers", name: "Valley Plumbing and Drain Cleaning", phone: "801-369-6870", city: "Lehi", note: "24/7 service across Utah County" },
  { id: "plumbers-3",  industry: "Plumbers", name: "AAA Action Quick Response Plumbing", phone: "801-636-3333", city: "Provo", note: "24/7 emergency plumbing" },
  { id: "plumbers-4",  industry: "Plumbers", name: "Professional Plumbing Systems (PPS)", phone: "801-794-3636", city: "Springville", note: "Office line; serves all Utah County" },
  { id: "plumbers-5",  industry: "Plumbers", name: "MAC Plumbing & Heating", phone: "801-361-6842", city: "American Fork", note: "Serves AF, Highland, Cedar Hills, Lehi" },
  { id: "plumbers-6",  industry: "Plumbers", name: "Prime Plumbing", phone: "801-494-1790", city: "Spanish Fork", note: "Serves Springville, Payson, Spanish Fork" },
  { id: "plumbers-7",  industry: "Plumbers", name: "Roto-Rooter Plumbing", phone: "801-736-0055", city: "American Fork", note: "Emergency plumbing, Utah Valley" },
  { id: "plumbers-8",  industry: "Plumbers", name: "Sunset Plumbing Utah", phone: "385-231-1713", city: "Springville", note: "Springville/Spanish Fork/Payson area" },
  { id: "plumbers-9",  industry: "Plumbers", name: "Thomas Plumbing & Affordable Drain Service", phone: "801-889-9539", city: "Spanish Fork", note: "Drain service, Utah County" },
  { id: "plumbers-10", industry: "Plumbers", name: "Whipple Service Champions", phone: "385-786-9891", city: "Provo", note: "Plumbing, heating, cooling, electrical" },
  { id: "plumbers-11", industry: "Plumbers", name: "PPS After-Hours Emergency", phone: "801-835-5629", city: "Springville", note: "24-hour emergency plumbing" },

  // --- Electricians ---
  { id: "electricians-1",  industry: "Electricians", name: "Same Day Electric", phone: "801-361-1502", city: "Orem", note: "Serves Provo, Orem, AF, Lehi, PG" },
  { id: "electricians-2",  industry: "Electricians", name: "Bar H Bar Electric", phone: "385-257-3541", city: "Lehi", note: "Serves Lehi, PG, American Fork" },
  { id: "electricians-3",  industry: "Electricians", name: "Tri-Phase Electric", phone: "801-756-6008", city: "American Fork", note: "775 E Utah Valley Dr" },
  { id: "electricians-4",  industry: "Electricians", name: "EZ Electric", phone: "385-220-7312", city: "American Fork", note: "Residential/commercial electrical" },
  { id: "electricians-5",  industry: "Electricians", name: "High Altitude Electric", phone: "801-473-4481", city: "Spanish Fork", note: "7310 S 3200 W; serves Utah County" },
  { id: "electricians-6",  industry: "Electricians", name: "Envision Electric", phone: "801-509-1314", city: "Lehi", note: "24+ years experience, Northern Utah" },
  { id: "electricians-7",  industry: "Electricians", name: "Mint Electric", phone: "801-473-0901", city: "Mapleton", note: "Mapleton/Springville area" },
  { id: "electricians-8",  industry: "Electricians", name: "Haupt Electrical", phone: "801-489-6565", city: "Mapleton", note: "312 N 1600 W" },
  { id: "electricians-9",  industry: "Electricians", name: "CV Electric", phone: "801-489-3503", city: "Mapleton", note: "927 E 1200 N" },
  { id: "electricians-10", industry: "Electricians", name: "O'Connor's Electrical", phone: "844-484-2612", city: "Provo", note: "24/7 emergency, statewide" },
  { id: "electricians-11", industry: "Electricians", name: "Callahan Electric", phone: "385-402-6220", city: "Pleasant Grove", note: "348 S 2000 W area" },
  { id: "electricians-12", industry: "Electricians", name: "Same Day Electric (alt line)", phone: "801-900-4064", city: "Provo", note: "Provo/Orem electrical" },

  // --- Mechanics ---
  { id: "mechanics-1",  industry: "Mechanics", name: "Doug's Auto Repair", phone: "801-224-4055", city: "Orem", note: "673 E 1775 S" },
  { id: "mechanics-2",  industry: "Mechanics", name: "Clegg Auto Provo", phone: "801-374-8708", city: "Provo", note: "546 N Freedom Blvd" },
  { id: "mechanics-3",  industry: "Mechanics", name: "Certified Tire & Service", phone: "801-426-5535", city: "Provo", note: "Auto mechanic and tires" },
  { id: "mechanics-4",  industry: "Mechanics", name: "Computune Certified Auto Repair", phone: "385-375-3025", city: "Provo", note: "1272 N 300 W" },
  { id: "mechanics-5",  industry: "Mechanics", name: "Master AutoTech (Provo)", phone: "801-228-0044", city: "Provo", note: "825 W Center St" },
  { id: "mechanics-6",  industry: "Mechanics", name: "Master AutoTech (Orem)", phone: "801-228-0045", city: "Orem", note: "1795 N State St" },
  { id: "mechanics-7",  industry: "Mechanics", name: "Garrin's Automotive", phone: "801-766-9834", city: "Lehi", note: "266 E Main St" },
  { id: "mechanics-8",  industry: "Mechanics", name: "Rogers Automotive", phone: "801-768-2590", city: "Lehi", note: "198 W State St" },
  { id: "mechanics-9",  industry: "Mechanics", name: "Main Street Mechanic", phone: "801-756-2661", city: "American Fork", note: "337 W Main St" },
  { id: "mechanics-10", industry: "Mechanics", name: "Sam's Automotive Repair", phone: "801-499-6782", city: "Lehi", note: "681 E State St; serves American Fork" },
  { id: "mechanics-11", industry: "Mechanics", name: "Big O Tires (Provo)", phone: "801-374-1177", city: "Provo", note: "1461 N State St; repair and tires" },
  { id: "mechanics-12", industry: "Mechanics", name: "Big O Tires (Orem)", phone: "801-224-1177", city: "Orem", note: "703 N State St" },
  { id: "mechanics-13", industry: "Mechanics", name: "Burt Brothers Tire & Service (Highland)", phone: "801-492-6300", city: "Highland", note: "10918 Town Center Blvd" },
  { id: "mechanics-14", industry: "Mechanics", name: "Big O Tires (Lehi)", phone: "801-917-6062", city: "Lehi", note: "144 N 850 E" },
  { id: "mechanics-15", industry: "Mechanics", name: "Cascade Collision Repair", phone: "801-373-8020", city: "Provo", note: "1155 S State St; collision/auto body" },

  // --- Restaurants ---
  { id: "restaurants-1",  industry: "Restaurants", name: "Black Sheep Cafe", phone: "801-754-4762", city: "Provo", note: "19 N University Ave; Southwestern" },
  { id: "restaurants-2",  industry: "Restaurants", name: "Bombay House", phone: "801-373-6677", city: "Provo", note: "463 N University Ave; Indian" },
  { id: "restaurants-3",  industry: "Restaurants", name: "Communal", phone: "801-373-8000", city: "Provo", note: "102 N University Ave; New American" },
  { id: "restaurants-4",  industry: "Restaurants", name: "J Dawgs", phone: "801-373-3294", city: "Provo", note: "858 N 700 E; hot dogs" },
  { id: "restaurants-5",  industry: "Restaurants", name: "Brick Oven", phone: "801-374-8800", city: "Provo", note: "111 E 800 N; pizza/Italian" },
  { id: "restaurants-6",  industry: "Restaurants", name: "Joe's Cafe", phone: "801-607-5377", city: "Orem", note: "1126 S State St; breakfast/brunch" },
  { id: "restaurants-7",  industry: "Restaurants", name: "Asa Ramen", phone: "801-842-1898", city: "Orem", note: "1120 S State St; ramen" },
  { id: "restaurants-8",  industry: "Restaurants", name: "Tamashi Ramen", phone: "801-691-1894", city: "Orem", note: "206 E University Pkwy; Japanese" },
  { id: "restaurants-9",  industry: "Restaurants", name: "Pizza Pie Cafe", phone: "801-226-4277", city: "Orem", note: "573 W 1600 N; pizza buffet" },
  { id: "restaurants-10", industry: "Restaurants", name: "Sabaidee Thai Cuisine", phone: "801-766-4076", city: "Lehi", note: "250 W State St; Thai" },
  { id: "restaurants-11", industry: "Restaurants", name: "Sol Agave", phone: "385-233-6756", city: "American Fork", note: "749 W 100 N; Mexican" },
  { id: "restaurants-12", industry: "Restaurants", name: "JCW's The Burger Boys", phone: "801-492-1762", city: "American Fork", note: "580 E State Rd; burgers" },
  { id: "restaurants-13", industry: "Restaurants", name: "Cafe Rio", phone: "801-210-5200", city: "Spanish Fork", note: "782 N 800 E; Mexican grill" },
  { id: "restaurants-14", industry: "Restaurants", name: "Five Guys", phone: "801-798-7878", city: "Spanish Fork", note: "529 E 1000 N; burgers" },
  { id: "restaurants-15", industry: "Restaurants", name: "Magleby's", phone: "801-370-1129", city: "Springville", note: "198 S Main St; American" },
  { id: "restaurants-16", industry: "Restaurants", name: "Texas Roadhouse", phone: "385-200-7356", city: "Spanish Fork", note: "508 E Commerce Way; steakhouse" },

  // --- Car Washes ---
  { id: "carwashes-1", industry: "Car Washes", name: "Quick Quack Car Wash", phone: "888-772-2792", city: "Provo", note: "Chain — shared call center (multiple Utah County locations)" },
  { id: "carwashes-2", industry: "Car Washes", name: "Wiggy Wash", phone: "385-355-6696", city: "Orem", note: "Wash + detailing (Orem/Spanish Fork/Springville)" },
  { id: "carwashes-3", industry: "Car Washes", name: "Mister Car Wash (Orem)", phone: "385-286-5733", city: "Orem", note: "1408 S State St" },
  { id: "carwashes-4", industry: "Car Washes", name: "Mister Car Wash (American Fork)", phone: "801-756-9699", city: "American Fork", note: "83 N West State Rd" },
  { id: "carwashes-5", industry: "Car Washes", name: "Take 5 Car Wash", phone: "385-324-2050", city: "Orem", note: "367 N State St" },
  { id: "carwashes-6", industry: "Car Washes", name: "Cleaner Bros Detailing", phone: "801-472-2066", city: "Orem", note: "Wash and detailing, Utah County" },
  { id: "carwashes-7", industry: "Car Washes", name: "Clean Mobile Detailing", phone: "801-997-5919", city: "Orem", note: "Mobile; serves Provo, Lehi, AF" },
  { id: "carwashes-8", industry: "Car Washes", name: "Express Wash", phone: "801-607-5733", city: "Orem", note: "75 N 1200 W; self-serve" },

  // --- HVAC ---
  { id: "hvac-1",  industry: "HVAC", name: "Authority Heating & Cooling", phone: "801-850-0833", city: "Lehi", note: "Family-owned since 2006; serves Lehi & Utah County" },
  { id: "hvac-2",  industry: "HVAC", name: "American HVAC", phone: "801-427-9456", city: "Orem", note: "Owner answers calls 6am-6pm; 40 yrs residential HVAC" },
  { id: "hvac-3",  industry: "HVAC", name: "HRC Climate Services", phone: "801-373-9440", city: "Provo", note: "Serves Provo, Orem, Spanish Fork, Payson" },
  { id: "hvac-4",  industry: "HVAC", name: "ABT Heating & Cooling", phone: "801-695-4626", city: "Provo", note: "AC & furnace service in Provo, Orem, Lehi" },
  { id: "hvac-5",  industry: "HVAC", name: "The Heating and Cooling Guys", phone: "385-412-5771", city: "Provo", note: "Locally owned and operated" },
  { id: "hvac-6",  industry: "HVAC", name: "SRV Heating and Air", phone: "801-923-6092", city: "Lehi", note: "24/7, same-day and weekend appointments" },
  { id: "hvac-7",  industry: "HVAC", name: "Gillette Heating and Air Conditioning", phone: "801-760-7724", city: "Saratoga Springs", note: "Serves Lehi, PG & north Utah County" },
  { id: "hvac-8",  industry: "HVAC", name: "Mr. Good Guy HVAC", phone: "385-208-7777", city: "American Fork", note: "Full-service contractor, AF area" },
  { id: "hvac-9",  industry: "HVAC", name: "The HVAC Guys", phone: "801-335-9017", city: "Payson", note: "Serves Payson, Springville, Spanish Fork" },
  { id: "hvac-10", industry: "HVAC", name: "Comfort Maxx Heating & Air Conditioning", phone: "385-999-2072", city: "Spanish Fork", note: "275 Arrowhead Trl; south county since 2007" },
  { id: "hvac-11", industry: "HVAC", name: "Triple-T Plumbing, Heating & Air", phone: "801-798-7711", city: "Spanish Fork", note: "1550 N Main St; HVAC + plumbing + electrical" },
  { id: "hvac-12", industry: "HVAC", name: "Professional Heating and Air Conditioning", phone: "801-785-3007", city: "Pleasant Grove", note: "396 S 100 E; family-owned 40+ years" },
  { id: "hvac-13", industry: "HVAC", name: "Comfort Pros Heating & Air", phone: "801-405-9034", city: "Pleasant Grove", note: "Family-owned, AC repair in PG area" },
  { id: "hvac-14", industry: "HVAC", name: "Eagar Heating and Cooling", phone: "801-226-8367", city: "Orem", note: "646 S 1325 W; Mon-Fri local shop" },
  { id: "hvac-15", industry: "HVAC", name: "At Your Service Pros", phone: "801-876-5222", city: "Orem", note: "HVAC, plumbing & electrical across Utah County" },

  // --- Pest Control ---
  { id: "pestcontrol-1",  industry: "Pest Control", name: "Buffo's Termite & Pest Control", phone: "801-373-3940", city: "Provo", note: "Provo local, serving Utah 50+ years" },
  { id: "pestcontrol-2",  industry: "Pest Control", name: "AB Pest Control", phone: "801-829-7378", city: "Provo", note: "440 N University Ave Ste 103" },
  { id: "pestcontrol-3",  industry: "Pest Control", name: "Guardian Pest Control", phone: "801-225-6000", city: "Orem", note: "Utah-based, 20+ years, serves all Utah County" },
  { id: "pestcontrol-4",  industry: "Pest Control", name: "All Guard Pest Control", phone: "801-851-1812", city: "Orem", note: "51 W Center St; homes, HOAs & businesses" },
  { id: "pestcontrol-5",  industry: "Pest Control", name: "H2 Pest Control", phone: "801-980-0820", city: "Lehi", note: "Family & veteran-owned, 2791 N 750 E" },
  { id: "pestcontrol-6",  industry: "Pest Control", name: "Atlas Pest Services", phone: "801-717-9145", city: "Lehi", note: "Lehi-based, serves north Utah County" },
  { id: "pestcontrol-7",  industry: "Pest Control", name: "Jitterbug Pest Control", phone: "801-766-9390", city: "Lehi", note: "1300 W 650 S; Utah County line" },
  { id: "pestcontrol-8",  industry: "Pest Control", name: "Canyon Pest Control", phone: "801-231-5681", city: "American Fork", note: "Free estimates; serves Pleasant Grove" },
  { id: "pestcontrol-9",  industry: "Pest Control", name: "Aardvark Pest Solutions", phone: "801-477-8727", city: "Pleasant Grove", note: "1579 E 480 S; family owned, voted Best in Utah County" },
  { id: "pestcontrol-10", industry: "Pest Control", name: "Thorn Pest Solutions", phone: "800-626-1156", city: "Pleasant Grove", note: "484 W 220 S; commercial & residential" },
  { id: "pestcontrol-11", industry: "Pest Control", name: "Green Grounds Lawn & Pest", phone: "801-900-3808", city: "Orem", note: "Lawn + pest combo; Orem to Spanish Fork" },
  { id: "pestcontrol-12", industry: "Pest Control", name: "Proof Pest Control", phone: "801-999-1017", city: "Orem", note: "89 N 1330 W; Utah-founded" },
  { id: "pestcontrol-13", industry: "Pest Control", name: "Local Bug Guy", phone: "385-393-6737", city: "Spanish Fork", note: "Owner-operated; serves Springville/Payson/Mapleton" },
  { id: "pestcontrol-14", industry: "Pest Control", name: "Utah Pest", phone: "801-890-5211", city: "Saratoga Springs", note: "Serves NW Utah County" },
  { id: "pestcontrol-15", industry: "Pest Control", name: "Beeline Pest Control", phone: "801-655-5074", city: "Provo", note: "Utah-based regional; Provo, Orem, Lindon, PG, Springville" },

  // --- Lawn Care & Landscaping ---
  { id: "lawncare-1",  industry: "Lawn Care & Landscaping", name: "Edge Landscaping", phone: "801-618-4561", city: "Orem", note: "165 N 1330 W; serves Provo/Orem" },
  { id: "lawncare-2",  industry: "Lawn Care & Landscaping", name: "L&S Landscaping", phone: "801-502-0662", city: "Provo", note: "Serves Orem, Pleasant Grove, SLC" },
  { id: "lawncare-3",  industry: "Lawn Care & Landscaping", name: "Urban Forest Landscaping", phone: "801-671-8573", city: "Provo", note: "Provo & 18 Utah County communities" },
  { id: "lawncare-4",  industry: "Lawn Care & Landscaping", name: "J&H Landscaping", phone: "385-213-2539", city: "Provo", note: "Serves Provo, Lehi, Spanish Fork, Payson" },
  { id: "lawncare-5",  industry: "Lawn Care & Landscaping", name: "J & J Services", phone: "801-318-4999", city: "American Fork", note: "Landscaping/construction, 20+ yrs" },
  { id: "lawncare-6",  industry: "Lawn Care & Landscaping", name: "Lawn Thumbs", phone: "801-500-2140", city: "American Fork", note: "120 N Grant Ave; mowing, fertilization, aeration" },
  { id: "lawncare-7",  industry: "Lawn Care & Landscaping", name: "Bee Garden Landscape LLC", phone: "385-645-9210", city: "American Fork", note: "Serves Eagle Mtn, Pleasant Grove, Lehi" },
  { id: "lawncare-8",  industry: "Lawn Care & Landscaping", name: "Saratoga Mowing", phone: "801-810-5452", city: "Lehi", note: "Serves Saratoga Springs, Eagle Mtn, north county" },
  { id: "lawncare-9",  industry: "Lawn Care & Landscaping", name: "Guardian Lawn Care", phone: "801-225-4342", city: "Springville", note: "687 N 2000 W Ste 4; locally owned, 17+ yrs" },
  { id: "lawncare-10", industry: "Lawn Care & Landscaping", name: "Pure Green Yard Care", phone: "801-708-0102", city: "Lehi", note: "799 E 1475 N; Lehi & Utah County" },
  { id: "lawncare-11", industry: "Lawn Care & Landscaping", name: "Payson Lawn Care", phone: "801-616-6154", city: "Payson", note: "Full-service, south Utah County" },
  { id: "lawncare-12", industry: "Lawn Care & Landscaping", name: "Aloha Landscape & Lawn", phone: "801-755-3123", city: "Lehi", note: "663 N 1450 W; serves AF, Saratoga Springs, PG" },
  { id: "lawncare-13", industry: "Lawn Care & Landscaping", name: "Dave's Lawncare", phone: "801-602-2625", city: "Lehi", note: "Veteran-owned, lawn + sprinkler service" },
  { id: "lawncare-14", industry: "Lawn Care & Landscaping", name: "Utah Valley Lawn Care", phone: "801-899-9199", city: "Orem", note: "275 S Mountain Way Dr" },

  // --- Carpet Cleaning ---
  { id: "carpetcleaning-1",  industry: "Carpet Cleaning", name: "Pineapple Carpet Cleaning", phone: "801-890-3990", city: "American Fork", note: "73 N 490 W; serves Utah County to Payson" },
  { id: "carpetcleaning-2",  industry: "Carpet Cleaning", name: "Kelly's Deep Clean", phone: "801-756-4874", city: "American Fork", note: "Serves AF, Lehi, PG, Orem, Provo to Payson" },
  { id: "carpetcleaning-3",  industry: "Carpet Cleaning", name: "Pink's Carpet Cleaning", phone: "801-889-9183", city: "Lehi", note: "Owner-operated; serves Lehi/Alpine/Orem" },
  { id: "carpetcleaning-4",  industry: "Carpet Cleaning", name: "Boss Systems Carpet Cleaning", phone: "801-225-5750", city: "Provo", note: "396 E 1130 S; since 1999, all of Utah County" },
  { id: "carpetcleaning-5",  industry: "Carpet Cleaning", name: "AJS Carpet Cleaning", phone: "801-368-0705", city: "Orem", note: "1620 S 800 E; family business since 2000" },
  { id: "carpetcleaning-6",  industry: "Carpet Cleaning", name: "TruRinse", phone: "801-226-6827", city: "Orem", note: "Local Utah company 15+ yrs; all Utah County" },
  { id: "carpetcleaning-7",  industry: "Carpet Cleaning", name: "Utah Pros Carpet Cleaning", phone: "385-376-1376", city: "Provo", note: "BBB A+; serves Lehi to Payson" },
  { id: "carpetcleaning-8",  industry: "Carpet Cleaning", name: "EcoCarpet Cleaning", phone: "801-855-5696", city: "Orem", note: "176 State St; budget-friendly local cleaner" },
  { id: "carpetcleaning-9",  industry: "Carpet Cleaning", name: "Hello Clean Carpet Cleaning", phone: "385-250-0254", city: "Provo", note: "Small local outfit, Provo/Orem area" },
  { id: "carpetcleaning-10", industry: "Carpet Cleaning", name: "Power Plus Cleaning and Restoration", phone: "801-227-7387", city: "Orem", note: "801-CARPETS; cleaning + restoration" },
  { id: "carpetcleaning-11", industry: "Carpet Cleaning", name: "The Express Carpet Cleaning", phone: "385-895-6744", city: "Payson", note: "Serves Payson, Salem, Spanish Fork, Springville" },
  { id: "carpetcleaning-12", industry: "Carpet Cleaning", name: "Pristine Carpet Cleaning & Home Services", phone: "801-734-0634", city: "Springville", note: "Small local business, ~6 years running" },
  { id: "carpetcleaning-13", industry: "Carpet Cleaning", name: "Heaven's Best Carpet Cleaning of Utah County", phone: "801-910-4003", city: "Payson", note: "Locally owned franchise; 1-hr dry" },
  { id: "carpetcleaning-14", industry: "Carpet Cleaning", name: "Certified Chem-Dry", phone: "801-328-3599", city: "Orem", note: "Locally owned franchise; Provo, Orem, Lehi, AF" },
  { id: "carpetcleaning-15", industry: "Carpet Cleaning", name: "Precision Chem-Dry", phone: "801-905-1627", city: "Provo", note: "Locally owned franchise, county-wide" },

  // --- Garage Doors ---
  { id: "garagedoors-1",  industry: "Garage Doors", name: "Lowry Doors", phone: "801-252-5750", city: "Orem", note: "782 N State St; 4th-generation family business since 1950" },
  { id: "garagedoors-2",  industry: "Garage Doors", name: "Nova Doors", phone: "385-566-1249", city: "Orem", note: "1510 W 400 S Ste 3; repair + installation" },
  { id: "garagedoors-3",  industry: "Garage Doors", name: "Pinnacle Garage Doors", phone: "801-798-8272", city: "Orem", note: "1366 W 465 S; serves all Utah County" },
  { id: "garagedoors-4",  industry: "Garage Doors", name: "Provo Garage Door", phone: "801-895-3404", city: "Provo", note: "Serves Provo, Orem, Lehi, PG; free estimates" },
  { id: "garagedoors-5",  industry: "Garage Doors", name: "SureFix Garage Doors", phone: "801-210-8554", city: "Provo", note: "Locally owned; 24-hr, county-wide" },
  { id: "garagedoors-6",  industry: "Garage Doors", name: "My Guy Garage Door Repair", phone: "385-265-1093", city: "Lehi", note: "111 E Main St L2; also Springville shop, 15+ yrs" },
  { id: "garagedoors-7",  industry: "Garage Doors", name: "Powell Garage Doors", phone: "801-822-2474", city: "Lehi", note: "Shops in Lehi & Highland; res + commercial" },
  { id: "garagedoors-8",  industry: "Garage Doors", name: "A+ Garage Doors", phone: "801-316-3285", city: "Lehi", note: "Utah-based, 24/7; Lehi, Provo, Orem, Eagle Mtn" },
  { id: "garagedoors-9",  industry: "Garage Doors", name: "Affordable Garage Door Fix", phone: "385-213-1977", city: "American Fork", note: "Repair specialist, AF area" },
  { id: "garagedoors-10", industry: "Garage Doors", name: "A1 Garage Door Service Tech", phone: "801-759-3667", city: "American Fork", note: "Serves AF, Lehi, Provo; free estimates, 24/7" },
  { id: "garagedoors-11", industry: "Garage Doors", name: "Garage Door Repair LLC (GDR Utah)", phone: "801-477-0736", city: "Pleasant Grove", note: "Same-day residential repair, county-wide" },
  { id: "garagedoors-12", industry: "Garage Doors", name: "AAA Garage Door Inc", phone: "801-889-1985", city: "Orem", note: "Serves Utah & Salt Lake counties" },
  { id: "garagedoors-13", industry: "Garage Doors", name: "Dependable Door Systems Inc", phone: "801-849-9030", city: "Spanish Fork", note: "1932 N Main St storefront; 30+ yrs" },
  { id: "garagedoors-14", industry: "Garage Doors", name: "Intermountain Martin Door", phone: "801-404-1200", city: "Payson", note: "Replacements, springs, tune-ups" },

  // --- Roofing & Gutters ---
  { id: "roofing-1",  industry: "Roofing & Gutters", name: "A1 Roofing Utah", phone: "385-338-3151", city: "Orem", note: "415 W 1200 N Ste A; family-owned, 30+ yrs in Utah Valley" },
  { id: "roofing-2",  industry: "Roofing & Gutters", name: "Cascade Roofing Services, Inc.", phone: "801-831-4428", city: "Provo", note: "35+ years serving Utah County" },
  { id: "roofing-3",  industry: "Roofing & Gutters", name: "Custom Tech Roofing, Inc.", phone: "801-380-0202", city: "Payson", note: "208 S 1100 E; serves Provo and south county" },
  { id: "roofing-4",  industry: "Roofing & Gutters", name: "R1 Roofing & Exteriors", phone: "385-993-4487", city: "Lehi", note: "Serves AF, Orem, Provo, Lehi; roofing + exteriors" },
  { id: "roofing-5",  industry: "Roofing & Gutters", name: "M.W. Roofing", phone: "385-243-4458", city: "Spanish Fork", note: "Also Springville, Mapleton, Salem, Payson" },
  { id: "roofing-6",  industry: "Roofing & Gutters", name: "Roofing Services Consultants", phone: "801-471-4593", city: "Springville", note: "331 W 950 N" },
  { id: "roofing-7",  industry: "Roofing & Gutters", name: "Utah Roofing Experts", phone: "385-766-3464", city: "Spanish Fork", note: "Serves Spanish Fork and Springville" },
  { id: "roofing-8",  industry: "Roofing & Gutters", name: "Red Peaks Roofing Inc.", phone: "385-482-9707", city: "Saratoga Springs", note: "429 W 1560 N; metal roofing specialist" },
  { id: "roofing-9",  industry: "Roofing & Gutters", name: "Roofing Utah", phone: "385-799-8824", city: "Provo", note: "Repairs and maintenance, Provo & Lehi" },
  { id: "roofing-10", industry: "Roofing & Gutters", name: "Mi Techo Roofing", phone: "801-404-6896", city: "Pleasant Grove", note: "Roofing, siding, seamless gutters; PG & AF" },
  { id: "roofing-11", industry: "Roofing & Gutters", name: "Happy Valley Exteriors", phone: "801-874-3602", city: "American Fork", note: "Gutter guards and installs; copper/aluminum" },
  { id: "roofing-12", industry: "Roofing & Gutters", name: "Provo Seamless Gutters", phone: "801-669-9406", city: "Provo", note: "223 W Bulldog Blvd; serves Orem & PG" },
  { id: "roofing-13", industry: "Roofing & Gutters", name: "The Raingutter Guy", phone: "801-836-4735", city: "Orem", note: "Locally owned gutter contractor since 2003" },
  { id: "roofing-14", industry: "Roofing & Gutters", name: "Ace Gutter Inc.", phone: "801-790-4676", city: "Orem", note: "104 N 1200 W; gutters since 1998" },

  // --- Water Softeners ---
  { id: "watersofteners-1",  industry: "Water Softeners", name: "Flat Rate Water Softeners", phone: "801-559-7638", city: "Orem", note: "Owner-operated since 2016; flat-rate installs" },
  { id: "watersofteners-2",  industry: "Water Softeners", name: "Total Water LLC", phone: "801-796-0940", city: "Orem", note: "1111 S 1350 W Bldg C-110; filtration & treatment" },
  { id: "watersofteners-3",  industry: "Water Softeners", name: "Expert Water Systems", phone: "801-836-4112", city: "Lehi", note: "1236 W 800 S; budget installs, up to 15-yr warranty" },
  { id: "watersofteners-4",  industry: "Water Softeners", name: "Water Quest Corp", phone: "801-221-8892", city: "Orem", note: "Serves all Utah County" },
  { id: "watersofteners-5",  industry: "Water Softeners", name: "Intermountain Soft Water", phone: "801-225-5233", city: "Lindon", note: "220 S 1060 W; long-running local company" },
  { id: "watersofteners-6",  industry: "Water Softeners", name: "Salty Softeners LLC", phone: "385-977-4446", city: "Salem", note: "271 N 500 E; serves Spanish Fork/Springville" },
  { id: "watersofteners-7",  industry: "Water Softeners", name: "NuSoft Water Systems", phone: "801-448-7515", city: "Eagle Mountain", note: "Family owned; softeners + filtration" },
  { id: "watersofteners-8",  industry: "Water Softeners", name: "Element Water and Air", phone: "801-383-0880", city: "Lehi", note: "3300 Triumph Blvd Ste 100; all Utah County" },
  { id: "watersofteners-9",  industry: "Water Softeners", name: "Always Salty", phone: "801-854-0153", city: "Lehi", note: "Salt delivery & refill subscription, Lehi to Payson" },
  { id: "watersofteners-10", industry: "Water Softeners", name: "Simple Salt", phone: "801-821-1707", city: "Provo", note: "Salt delivery for homes/businesses, Provo/Orem/Springville" },
  { id: "watersofteners-11", industry: "Water Softeners", name: "Water Science", phone: "435-649-7154", city: "Provo", note: "Softeners, RO & salt delivery; serves Provo, Orem, Lehi, AF" },
  { id: "watersofteners-12", industry: "Water Softeners", name: "Royal Water Systems", phone: "801-980-2046", city: "Provo", note: "30+ yrs; sales/repair/install" },
  { id: "watersofteners-13", industry: "Water Softeners", name: "Kinetico Quality Water Systems", phone: "801-576-8600", city: "Draper", note: "Local Kinetico dealer; serves Provo/Orem, free water test" },

  // --- Dentists ---
  { id: "dentists-1",  industry: "Dentists", name: "Provo Family Dentistry", phone: "801-375-4600", city: "Provo", note: "1355 N University Ave Ste 310; independent family practice" },
  { id: "dentists-2",  industry: "Dentists", name: "Jeppson Dental", phone: "801-356-7701", city: "Provo", note: "86 N University Ave Ste 280; family & cosmetic since 2000" },
  { id: "dentists-3",  industry: "Dentists", name: "East Mountain Dental", phone: "801-377-0037", city: "Provo", note: "South Provo family dentistry" },
  { id: "dentists-4",  industry: "Dentists", name: "Thompson Orthodontics", phone: "801-375-7088", city: "Orem", note: "380 W Center St; braces & Invisalign" },
  { id: "dentists-5",  industry: "Dentists", name: "Nord Orthodontics", phone: "801-225-7141", city: "Orem", note: "805 S State St; also Eagle Mountain office" },
  { id: "dentists-6",  industry: "Dentists", name: "Dry Creek Pediatric Dentistry", phone: "801-766-2266", city: "Lehi", note: "3300 N Running Creek Way; kids-only dentistry" },
  { id: "dentists-7",  industry: "Dentists", name: "Hardy Smiles Pediatric Dentistry", phone: "801-331-8449", city: "Lehi", note: "3397 N 1200 E Ste 113; pediatric dental" },
  { id: "dentists-8",  industry: "Dentists", name: "Lehi Pediatric Dentistry", phone: "801-766-5557", city: "Lehi", note: "216 E Main St Ste 3; small local pediatric practice" },
  { id: "dentists-9",  industry: "Dentists", name: "Utah Valley Dental", phone: "801-756-4595", city: "American Fork", note: "General, family & cosmetic dentistry" },
  { id: "dentists-10", industry: "Dentists", name: "Brite Family Dental", phone: "801-756-0933", city: "American Fork", note: "291 N 300 E Ste B; independent family dental" },
  { id: "dentists-11", industry: "Dentists", name: "Grove Creek Dental", phone: "801-796-7779", city: "Pleasant Grove", note: "238 E State Rd #2; family dentist" },
  { id: "dentists-12", industry: "Dentists", name: "Canyon Dental Clinic", phone: "801-798-8496", city: "Spanish Fork", note: "665 E 300 S; family practice since 1992" },
  { id: "dentists-13", industry: "Dentists", name: "Buhler Dental Arts", phone: "801-794-9905", city: "Spanish Fork", note: "General & family dentistry" },
  { id: "dentists-14", industry: "Dentists", name: "Springville Dentistry", phone: "801-489-9456", city: "Springville", note: "378 E 400 S Ste 1; general, cosmetic & implants" },
  { id: "dentists-15", industry: "Dentists", name: "Johnson Family Dentistry", phone: "801-465-1390", city: "Payson", note: "822 S Hwy 198; family dentistry" },

  // --- Chiropractors ---
  { id: "chiropractors-1",  industry: "Chiropractors", name: "Alpine Spinal Rehab", phone: "801-374-2774", city: "Provo", note: "Family clinic since 1981, Dr. Jerry Clark" },
  { id: "chiropractors-2",  industry: "Chiropractors", name: "Spine Craft Utah", phone: "385-442-2225", city: "Provo", note: "Auto injury & spine care, Provo/Orem border" },
  { id: "chiropractors-3",  industry: "Chiropractors", name: "McClean Spine Care Specialists", phone: "801-373-1035", city: "Provo", note: "Spine care specialists" },
  { id: "chiropractors-4",  industry: "Chiropractors", name: "Utah Neck & Back Clinic", phone: "801-430-9244", city: "Provo", note: "719 N 1890 W, Unit 38B" },
  { id: "chiropractors-5",  industry: "Chiropractors", name: "Lonestar Chiropractic Center", phone: "801-434-4555", city: "Orem", note: "Chiro + massage + laser therapy" },
  { id: "chiropractors-6",  industry: "Chiropractors", name: "Spinal Rehab Specialists", phone: "801-590-7643", city: "Orem", note: "Patient-centered spinal rehab" },
  { id: "chiropractors-7",  industry: "Chiropractors", name: "Aspen Chiropractic Clinic", phone: "801-234-6325", city: "Orem", note: "489 S Orem Blvd, Dr. Paul Gurney" },
  { id: "chiropractors-8",  industry: "Chiropractors", name: "Foundation Chiropractic", phone: "801-226-2606", city: "Orem", note: "1425 S State St" },
  { id: "chiropractors-9",  industry: "Chiropractors", name: "Aznar Family Chiropractic", phone: "801-221-7012", city: "Orem", note: "Independent family practice" },
  { id: "chiropractors-10", industry: "Chiropractors", name: "Dry Creek Chiropractic", phone: "801-766-4113", city: "Lehi", note: "Dr. Aaron Walker" },
  { id: "chiropractors-11", industry: "Chiropractors", name: "Lehi Chiropractic", phone: "801-653-2900", city: "Lehi", note: "72 W Main St, downtown Lehi" },
  { id: "chiropractors-12", industry: "Chiropractors", name: "Doc Rock Stone Chiropractic", phone: "801-794-9494", city: "American Fork", note: "1042 E Bamberger Dr" },
  { id: "chiropractors-13", industry: "Chiropractors", name: "Rosquist Clinic", phone: "801-785-9411", city: "Pleasant Grove", note: "Chiropractic pain management clinic" },
  { id: "chiropractors-14", industry: "Chiropractors", name: "Cook Chiropractic", phone: "801-790-0185", city: "Spanish Fork", note: "Dr. Veloy Cook, natural relief & wellness" },
  { id: "chiropractors-15", industry: "Chiropractors", name: "Payson Salem Chiropractic", phone: "801-691-1194", city: "Payson", note: "1172 E 100 N Ste 9, Dr. Jon Krogue" },

  // --- Real Estate & Mortgage ---
  { id: "realestate-1",  industry: "Real Estate & Mortgage", name: "Presidio Real Estate Group", phone: "801-251-6683", city: "Lehi", note: "Local independent brokerage HQ'd in Lehi; luxury & residential" },
  { id: "realestate-2",  industry: "Real Estate & Mortgage", name: "Zander Real Estate Team", phone: "385-432-5538", city: "Provo", note: "High-volume local agent team" },
  { id: "realestate-3",  industry: "Real Estate & Mortgage", name: "Ashley Jensen & Associates", phone: "801-830-1717", city: "Provo", note: "Agent team, 2533 N 460 E" },
  { id: "realestate-4",  industry: "Real Estate & Mortgage", name: "Vision Real Estate", phone: "801-375-6800", city: "Provo", note: "Independent brokerage + property mgmt, 980 W Center St" },
  { id: "realestate-5",  industry: "Real Estate & Mortgage", name: "Kenny Parcell Team", phone: "801-794-7777", city: "Spanish Fork", note: "Well-known Utah Valley team, 648 N 900 E" },
  { id: "realestate-6",  industry: "Real Estate & Mortgage", name: "Harvest Park Group", phone: "801-232-3434", city: "Spanish Fork", note: "Local team focused on south Utah County" },
  { id: "realestate-7",  industry: "Real Estate & Mortgage", name: "Kim Brown - Bill Brown Realty", phone: "801-427-9420", city: "Springville", note: "Owner/principal broker, independent shop at 262 S Main St" },
  { id: "realestate-8",  industry: "Real Estate & Mortgage", name: "Aren Bybee - Bybee + Co Realty", phone: "801-830-0618", city: "Payson", note: "Team lead serving Payson/Elk Ridge area" },
  { id: "realestate-9",  industry: "Real Estate & Mortgage", name: "Palomores Properties (Kellie Knowles)", phone: "385-208-3338", city: "Saratoga Springs", note: "Local agent, Saratoga Springs based" },
  { id: "realestate-10", industry: "Real Estate & Mortgage", name: "Red Sign Real Estate Team", phone: "801-733-7446", city: "Orem", note: "Independent team, 998 N 1200 W" },
  { id: "realestate-11", industry: "Real Estate & Mortgage", name: "Security Home Mortgage", phone: "866-764-0111", city: "Orem", note: "Local mortgage broker, 576 S State St" },
  { id: "realestate-12", industry: "Real Estate & Mortgage", name: "First Colony Mortgage (Orem Boulevard)", phone: "801-854-1111", city: "Orem", note: "Utah County-based lender, local branch office" },
  { id: "realestate-13", industry: "Real Estate & Mortgage", name: "Randy Smith - Equity Real Estate", phone: "801-830-1995", city: "American Fork", note: "Branch broker, Equity Real Estate (Results) office" },
  { id: "realestate-14", industry: "Real Estate & Mortgage", name: "Stephanie Davis - Presidio Real Estate", phone: "801-367-1174", city: "Spanish Fork", note: "Individual agent serving south Utah County" },
  { id: "realestate-15", industry: "Real Estate & Mortgage", name: "Denise Martin - Orem's Nicest Realtor", phone: "801-602-9552", city: "Orem", note: "Individual agent who markets herself personally" },

  // --- Home Security & Smart Home ---
  { id: "homesecurity-1",  industry: "Home Security & Smart Home", name: "Zions Security Alarms", phone: "801-770-2806", city: "American Fork", note: "Local ADT-authorized dealer since 2001; alarms, cameras, monitoring" },
  { id: "homesecurity-2",  industry: "Home Security & Smart Home", name: "ARCO Lock & Security", phone: "801-374-2986", city: "Provo", note: "Alarm.com systems, smart locks, access control + locksmith; Provo to Lehi" },
  { id: "homesecurity-3",  industry: "Home Security & Smart Home", name: "Reed's Built-Ins", phone: "801-375-4919", city: "Provo", note: "Family AV/automation shop since 1971; smart home, theater, security" },
  { id: "homesecurity-4",  industry: "Home Security & Smart Home", name: "Sentinel Systems", phone: "801-233-9233", city: "Provo", note: "Integrator since 2007; IP video surveillance, access control" },
  { id: "homesecurity-5",  industry: "Home Security & Smart Home", name: "Payson Lock & Key", phone: "801-465-9621", city: "Payson", note: "4K CCTV + access control since 1995; south Utah County" },
  { id: "homesecurity-6",  industry: "Home Security & Smart Home", name: "Cams Custom AV", phone: "801-735-8056", city: "Springville", note: "Security cameras, theaters, prewiring, whole-home WiFi; all Utah County" },
  { id: "homesecurity-7",  industry: "Home Security & Smart Home", name: "K2 Home Solutions", phone: "801-362-7070", city: "Lehi", note: "Smart home installs (Ring, cameras, thermostats); founded 2014" },
  { id: "homesecurity-8",  industry: "Home Security & Smart Home", name: "Onyx Automation", phone: "801-702-9913", city: "Orem", note: "Home automation/AV integrator; works with Utah Valley builders" },
  { id: "homesecurity-9",  industry: "Home Security & Smart Home", name: "Greenline Home Solutions", phone: "801-344-6691", city: "Lehi", note: "AV/home theater and smart home integrator; UVHBA member" },
  { id: "homesecurity-10", industry: "Home Security & Smart Home", name: "Alpine Communications", phone: "801-372-2623", city: "Alpine", note: "Low-voltage AV/communications installer; north Utah County" },
  { id: "homesecurity-11", industry: "Home Security & Smart Home", name: "Harmony Audio", phone: "801-610-9441", city: "Eagle Mountain", note: "Home theater/audio and smart home installs" },
  { id: "homesecurity-12", industry: "Home Security & Smart Home", name: "Cranked Up Audio Visual", phone: "801-787-9153", city: "Eagle Mountain", note: "AV/home theater installer; Eagle Mtn-Saratoga Springs corridor" },
  { id: "homesecurity-13", industry: "Home Security & Smart Home", name: "Building Electronic Systems Technology", phone: "801-360-9310", city: "Spanish Fork", note: "BBB-listed security camera installer, south county" },
  { id: "homesecurity-14", industry: "Home Security & Smart Home", name: "Tri-City Alarm Co", phone: "801-463-3733", city: "Salt Lake City", note: "Independent alarm company with monitoring; serves Provo/Orem" },
  { id: "homesecurity-15", industry: "Home Security & Smart Home", name: "Argenta Solutions", phone: "801-996-3146", city: "Sandy", note: "Design-build smart home integrator; serves Eagle Mountain" }
];
